### ISSUE TITLE
Auto Update Bing Images CI failed

### ISSUE THREAD

**Issue by cubeyu** [dmego/dmegohome.github.io#26]
github-actions[bot]@users.noreply.github.com这个账户添加合作者他也没同意,token权限和你的注意事项是一样的
`Run ad-m/github-push-action@master
Push to branch main
remote: Permission to cubeyu/cubeyu.github.io.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/cubeyu/cubeyu.github.io.git/': The requested URL returned error: 403
Error: Invalid exit code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:29:21)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:1[6](https://github.com/cubeyu/cubeyu.github.io/actions/runs/5134944884/jobs/9239669296#step:6:7))
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 128
}
Error: Invalid exit code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:29:21)
    at ChildProcess.emit (node:events:52[7](https://github.com/cubeyu/cubeyu.github.io/actions/runs/5134944884/jobs/9239669296#step:6:8):2[8](https://github.com/cubeyu/cubeyu.github.io/actions/runs/5134944884/jobs/9239669296#step:6:9))
    at maybeClose (node:internal/child_process:10[9](https://github.com/cubeyu/cubeyu.github.io/actions/runs/5134944884/jobs/9239669296#step:6:10)2:[16](https://github.com/cubeyu/cubeyu.github.io/actions/runs/5134944884/jobs/9239669296#step:6:17))
    at Process.ChildProcess._handle.onexit **(node:internal/child_process:302:5)`**

**Comment by dmego** [comment]
@cubeyu 看看这个 issue，和你的问题一样，可以参考解决：https://github.com/ad-m/github-push-action/issues/96

**Comment by cubeyu** [comment]
谢谢大大
